### PR TITLE
Apply doc styleguide and update React.render to ReactDom.render (vers…

### PR DESCRIPTION
**Pull request by FranDelaCasa**
…ion 0.14)

### CODE REVIEW

**Comment by danderu** [comment]
:+1: muy bien! :)

**Comment by FranDelaCasa** [comment]
@scm-spain/react-devs, review, please ;)

**Comment by danderu** [comment]
:+1:

**Comment by danderu** [comment]
@FranDelaCasa Notice that it has conflicts and can't be merged

**Pull request closed without merging**
