### PR TITLE
Doc revision

### PR DESCRIPTION
**Pull request by FranDelaCasa**
@danderu @davecarter @carlosvillu, please, review :)

### CODE REVIEW

**Comment by danderu** [comment]
@FranDelaCasa please resolve the merging conflicts first

**Comment by FranDelaCasa** [comment]
Conflicts resolved, @danderu

**Comment by FranDelaCasa** [comment]
@danderu @carlosvillu @davecarter review, please :)

**Comment by danderu** [comment]
:+1:

**Comment by davecarter** [comment]
:+1:

**Pull request merged**
